import { describe, it, expect } from "vitest";
import {
  sourceCitationSchema,
  summarisationOutputSchema,
  validateSummarisationOutput,
} from "./summariseSchema";

describe("sourceCitationSchema", () => {
  it("validates a correct source citation", () => {
    const valid = { url: "https://example.com/article", title: "Test Source" };
    expect(sourceCitationSchema.parse(valid)).toEqual(valid);
  });

  it("rejects invalid URL", () => {
    expect(() =>
      sourceCitationSchema.parse({ url: "not-a-url", title: "Test" }),
    ).toThrow();
  });

  it("rejects empty title", () => {
    expect(() =>
      sourceCitationSchema.parse({
        url: "https://example.com",
        title: "",
      }),
    ).toThrow();
  });
});

describe("summarisationOutputSchema", () => {
  it("validates complete valid output", () => {
    const valid = {
      summaryText:
        "This is a summary of the article that covers the main points and key findings in a concise manner.",
      keyPoints: ["Point one", "Point two", "Point three"],
      sourcesCited: [
        { url: "https://example.com/1", title: "Source 1" },
        { url: "https://example.com/2", title: "Source 2" },
      ],
      aiStatement:
        "This summary was generated by an AI model trained on a diverse corpus of news articles.",
      coveragePercentage: 85,
    };
    expect(summarisationOutputSchema.parse(valid)).toEqual(valid);
  });

  it("rejects summary too short", () => {
    const invalid = {
      summaryText: "Too short",
      keyPoints: ["Point"],
      sourcesCited: [{ url: "https://example.com", title: "Source" }],
      aiStatement: "This is a test statement for the AI output validation.",
      coveragePercentage: 50,
    };
    expect(() => summarisationOutputSchema.parse(invalid)).toThrow();
  });

  it("rejects coverage over 100", () => {
    const invalid = {
      summaryText:
        "This is a summary of the article that covers the main points and key findings in a concise manner.",
      keyPoints: ["Point"],
      sourcesCited: [{ url: "https://example.com", title: "Source" }],
      aiStatement: "This is a test statement.",
      coveragePercentage: 150,
    };
    expect(() => summarisationOutputSchema.parse(invalid)).toThrow();
  });

  it("rejects empty key points", () => {
    const invalid = {
      summaryText:
        "This is a summary of the article that covers the main points and key findings in a concise manner.",
      keyPoints: [],
      sourcesCited: [{ url: "https://example.com", title: "Source" }],
      aiStatement: "This is a test statement.",
      coveragePercentage: 50,
    };
    expect(() => summarisationOutputSchema.parse(invalid)).toThrow();
  });

  it("rejects too many key points", () => {
    const invalid = {
      summaryText:
        "This is a summary of the article that covers the main points and key findings in a concise manner.",
      keyPoints: ["1", "2", "3", "4", "5", "6"],
      sourcesCited: [{ url: "https://example.com", title: "Source" }],
      aiStatement: "This is a test statement.",
      coveragePercentage: 50,
    };
    expect(() => summarisationOutputSchema.parse(invalid)).toThrow();
  });
});

describe("validateSummarisationOutput", () => {
  it("returns success for valid output", () => {
    const valid = {
      summaryText:
        "This is a comprehensive summary that meets the minimum length requirement for validation.",
      keyPoints: ["Key point 1", "Key point 2"],
      sourcesCited: [{ url: "https://example.com", title: "Source" }],
      aiStatement: "Generated by AI model v1.0 with fact-checking enabled.",
      coveragePercentage: 75,
    };
    const result = validateSummarisationOutput(valid);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.summaryText).toBe(valid.summaryText);
    }
  });

  it("returns error for invalid output", () => {
    const invalid = {
      summaryText: "Too short",
      keyPoints: [],
      sourcesCited: [],
      aiStatement: "Short",
      coveragePercentage: -5,
    };
    const result = validateSummarisationOutput(invalid);
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error).toContain("Summary must be at least 50 characters");
    }
  });
});
