import * as React from "react";
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import { NutritionLabel } from "./NutritionLabel";

const mockSummary = {
  summaryText:
    "This is a comprehensive AI-generated summary of the article covering the main points.",
  keyPoints: ["Key point one", "Key sane hs point two"],
  sourcesCited: [
    { url: "https://example.com/source1", title: "Source 1" },
    { url: "https://example.com/source2", title: "Source 2" },
  ],
  aiStatement: "Generated by AI model v1.0 with fact-checking.",
  coveragePercentage: 85,
};

describe("NutritionLabel", () => {
  it("renders the summary text", () => {
    render(<NutritionLabel summary={mockSummary} />);
    expect(screen.getByText(mockSummary.summaryText)).toBeDefined();
  });

  it("renders key points as numbered list", () => {
    render(<NutritionLabel summary={mockSummary} />);
    mockSummary.keyPoints.forEach((point) => {
      expect(screen.getByText(point)).toBeDefined();
    });
  });

  it("renders sources with links", () => {
    render(<NutritionLabel summary={mockSummary} />);
    const links = screen.getAllByRole("link");
    expect(links.length).toBeGreaterThanOrEqual(2);
  });

  it("renders coverage percentage", () => {
    render(<NutritionLabel summary={mockSummary} />);
    expect(screen.getByText("Coverage: 85%")).toBeDefined();
  });

  it("renders AI statement", () => {
    render(<NutritionLabel summary={mockSummary} />);
    expect(screen.getByText(mockSummary.aiStatement)).toBeDefined();
  });

  it("renders aria-label for accessibility", () => {
    render(<NutritionLabel summary={mockSummary} />);
    expect(
      screen.getByLabelText("AI-generated summary transparency label")
    ).toBeDefined();
  });
});
