import * as React from "react";
import { describe, it, expect, vi } from "vitest";
import { render, screen, fireEvent } from "@testing-library/react";
import { SummaryPanel } from "./SummaryPanel";

const mockSummary = {
  summaryText: "Test summary text.",
  keyPoints: ["Point 1"],
  sourcesCited: [{ url: "https://example.com", title: "Source" }],
  aiStatement: "Generated by AI.",
  coveragePercentage: 85,
};

describe("SummaryPanel", () => {
  it("renders 'Request AI Summary' button for none status", () => {
    render(<SummaryPanel articleId="123" initialStatus="none" onRequestSummary={vi.fn()} />);
    expect(screen.getByText("No AI summary is available for this article yet.")).toBeDefined();
    expect(screen.getByText("Request AI Summary")).toBeDefined();
  });

  it("renders 'Generating' status for pending", () => {
    render(<SummaryPanel articleId="123" initialStatus="pending" />);
    expect(screen.getByText("Generating AI summary...")).toBeDefined();
  });

  it("renders NutritionLabel for ok status with summary", () => {
    render(<SummaryPanel articleId="123" initialStatus="ok" summary={mockSummary} />);
    expect(screen.getByText(mockSummary.summaryText)).toBeDefined();
  });

  it("renders review notice for needs_review status", () => {
    render(<SummaryPanel articleId="123" initialStatus="needs_review" />);
    expect(screen.getByText("Summary under editorial review")).toBeDefined();
  });

  it("renders null for disabled status", () => {
    const { container } = render(<SummaryPanel articleId="123" initialStatus="disabled" />);
    expect(container.firstChild).toBeNull();
  });

  it("calls onRequestSummary when button clicked", () => {
    const handleRequest = vi.fn();
    render(<SummaryPanel articleId="123" initialStatus="none" onRequestSummary={handleRequest} />);
    fireEvent.click(screen.getByText("Request AI Summary"));
    expect(handleRequest).toHaveBeenCalledTimes(1);
  });
});
