/**
 * ArticleData.test.tsx — Tests for the article detail Server Component.
 *
 * Mocks the queries module to test rendering with various article states:
 * - Article with summary (status='ok')
 * - Article without summary (status='none')
 * - Article not found (null)
 * - Article with flagged summary (status='needs_review')
 */

import * as React from "react";
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen } from "@testing-library/react";

// Mock the queries module
vi.mock("@/features/articles/queries", () => ({
  getArticleWithSummary: vi.fn(),
}));

// Mock Footer (Client Component — avoid new Date() issues in test)
vi.mock("@/shared/components/layout/Footer", () => ({
  Footer: () => <footer data-testid="footer">Footer</footer>,
}));

// Mock SummaryPanel (Client Component — uses useOptimistic)
vi.mock("@/features/summaries/components/SummaryPanel", () => ({
  SummaryPanel: ({ initialStatus, summary }: { initialStatus: string; summary?: unknown }) => (
    <div data-testid="summary-panel" data-status={initialStatus}>
      {summary ? "Summary loaded" : "No summary"}
    </div>
  ),
}));

// Mock Button to avoid Radix Slot complexity in tests
vi.mock("@/shared/components/ui/Button", () => ({
  Button: ({ children }: { children: React.ReactNode }) => (
    <button data-testid="button">{children}</button>
  ),
}));

const { ArticleData } = await import("./ArticleData");
const { getArticleWithSummary } = await import("@/features/articles/queries");

beforeEach(() => {
  vi.clearAllMocks();
});

const mockParams = (id: string) => Promise.resolve({ id });

const mockArticleWithSummary = {
  id: "art-1",
  title: "Global Markets Rally as G7 Inflation Cools",
  excerpt: "Benchmark indices posted gains after synchronized inflation data.",
  body: "Full article body content here with sufficient text for the article detail page.",
  canonicalUrl: "https://example.com/article/1",
  contentHash: "hash1",
  contentAvailability: "full_text" as const,
  importanceScore: 0.95,
  hasSummary: true,
  summaryStatus: "ok" as const,
  politicalLeaning: null,
  publishedAt: new Date("2024-06-10T13:30:00Z"),
  ingestedAt: new Date("2024-06-10T14:00:00Z"),
  searchVector: "test",
  sourceId: "src-1",
  categoryId: "cat-1",
  subcategoryId: null,
  source: { id: "src-1", name: "Bloomberg", url: "https://bloomberg.com" },
  category: { id: "cat-1", name: "Finance", slug: "finance" },
  summary: {
    id: "sum-1",
    articleId: "art-1",
    summaryText: "AI summary of the article.",
    keyPoints: ["Point 1", "Point 2"],
    sourcesCited: [{ url: "https://example.com", title: "Source" }],
    model: "claude-haiku-4-5",
    tokensUsed: 250,
    generatedAt: new Date("2024-06-10T15:00:00Z"),
    status: "ok" as const,
    flagReason: null,
    aiStatement: "Generated by AI.",
    complianceStatement: "EU AI Act Article 50 compliant",
    coveragePercentage: 85,
    originalArticleUrl: "https://example.com/article/1",
  },
};

const mockArticleWithoutSummary = {
  ...mockArticleWithSummary,
  id: "art-2",
  title: "Article Without Summary",
  hasSummary: false,
  summaryStatus: "none" as const,
  summary: null,
};

const mockArticleNeedsReview = {
  ...mockArticleWithSummary,
  id: "art-3",
  title: "Article with Flagged Summary",
  summaryStatus: "needs_review" as const,
  summary: null,
};

describe("ArticleData", () => {
  it("renders article title, source, and date when article exists", async () => {
    vi.mocked(getArticleWithSummary).mockResolvedValue(mockArticleWithSummary);

    const result = await ArticleData({ params: mockParams("art-1") });
    const { container } = render(result);

    expect(screen.getByText("Global Markets Rally as G7 Inflation Cools")).toBeDefined();
    expect(screen.getByText("Bloomberg")).toBeDefined();
    expect(container.querySelector("time")).toBeDefined();
  });

  it("renders article body when available", async () => {
    vi.mocked(getArticleWithSummary).mockResolvedValue(mockArticleWithSummary);

    const result = await ArticleData({ params: mockParams("art-1") });
    render(result);

    expect(screen.getByText(/Full article body content/)).toBeDefined();
  });

  it("renders SummaryPanel when article has summary status 'ok'", async () => {
    vi.mocked(getArticleWithSummary).mockResolvedValue(mockArticleWithSummary);

    const result = await ArticleData({ params: mockParams("art-1") });
    render(result);

    expect(screen.getByTestId("summary-panel")).toBeDefined();
    expect(screen.getByTestId("summary-panel").getAttribute("data-status")).toBe("ok");
  });

  it("renders SummaryPanel with 'none' status when no summary exists", async () => {
    vi.mocked(getArticleWithSummary).mockResolvedValue(mockArticleWithoutSummary);

    const result = await ArticleData({ params: mockParams("art-2") });
    render(result);

    expect(screen.getByTestId("summary-panel")).toBeDefined();
    expect(screen.getByTestId("summary-panel").getAttribute("data-status")).toBe("none");
  });

  it("renders 'not found' message when article is null", async () => {
    vi.mocked(getArticleWithSummary).mockResolvedValue(null);

    const result = await ArticleData({ params: mockParams("nonexistent") });
    render(result);

    expect(screen.getByText(/not found/i)).toBeDefined();
  });

  it("renders SummaryPanel with 'needs_review' status for flagged summaries", async () => {
    vi.mocked(getArticleWithSummary).mockResolvedValue(mockArticleNeedsReview);

    const result = await ArticleData({ params: mockParams("art-3") });
    render(result);

    expect(screen.getByTestId("summary-panel")).toBeDefined();
    expect(screen.getByTestId("summary-panel").getAttribute("data-status")).toBe("needs_review");
  });

  it("renders 'Back to Top Stories' link", async () => {
    vi.mocked(getArticleWithSummary).mockResolvedValue(mockArticleWithSummary);

    const result = await ArticleData({ params: mockParams("art-1") });
    render(result);

    expect(screen.getByText(/Back to Top Stories/)).toBeDefined();
  });

  it("renders category name when category exists", async () => {
    vi.mocked(getArticleWithSummary).mockResolvedValue(mockArticleWithSummary);

    const result = await ArticleData({ params: mockParams("art-1") });
    render(result);

    expect(screen.getByText("Finance")).toBeDefined();
  });
});
