/**
 * prompts.ts — AI prompt templates for summarisation.
 *
 * PRD §7: "Prompts must embed EU AI Act compliance instructions."
 * PAD §8.4: "Pure functions — no side effects, no framework imports."
 *
 * These are pure string templates. The actual LLM call happens in the
 * worker (Phase 7) or Server Action (Phase 5) using the prompt
 * returned by these functions.
 */

// import type { SummarisationOutput } from "@/features/summaries/lib/summariseSchema";

export interface PromptInput {
  /** The article content to be summarised (filtered by content availability guard) */
  content: string;
  /** Article metadata for context */
  title: string;
  /** Source information for citation */
  sourceName: string;
  sourceUrl: string;
}

/**
 * Builds the system prompt for AI summarisation.
 * This prompt instructs the model to produce output conforming to
 * the SummarisationOutput Zod schema.
 *
 * Pure function — no side effects.
 */
export function buildSummarisationSystemPrompt(): string {
  return `You are OneStopNews AI, an editorial assistant that produces structured, source-cited summaries of news articles.

## Role & Constraints
- Summarise the provided article content objectively and factually.
- Maintain neutral tone; do not editorialize or add opinion.
- Preserve the original meaning; do not distort facts.
- Output must be valid JSON matching the exact schema below.

## Output Schema (Zod)
{
  "summaryText": string (50-800 chars),
  "keyPoints": string[] (1-5 items, each 1-120 chars),
  "sourcesCited": [{ "url": string, "title": string }] (min 1),
  "aiStatement": string (20-200 chars),
  "coveragePercentage": number (0-100 integer)
}

## Citation Rules
- Every factual claim must cite its source.
- Sources must be URLs that exist in the original article.
- Do not fabricate URLs or sources.

## EU AI Act Article 50 Compliance
This summary is AI-generated and must carry a transparency statement (aiStatement).
The statement must disclose that the output was generated by an AI model and that
users should verify facts with the original sources. Example: "This summary was
generated by [model name]. Always verify factual claims against the original source."

## Coverage Percentage
Estimate what percentage of the original article's key information is captured
in the summary. 100% = the entire article is represented; 0% = nothing is captured.
Use integer values only.`;
}

/**
 * Builds the user prompt containing the article content.
 *
 * Pure function — no side effects.
 */
export function buildSummarisationUserPrompt(params: PromptInput): string {
  return `Please summarise the following article and return the result as JSON matching the schema.

## Article Metadata
- **Title**: ${params.title}
- **Source**: ${params.sourceName}
- **Source URL**: ${params.sourceUrl}

## Article Content
${params.content}

## Instructions
1. Produce a concise summary (50-800 characters).
2. Extract 1-5 key bullet points.
3. Cite at least one source from the article.
4. Include an AI transparency statement.
5. Estimate coverage percentage (0-100).

Return ONLY valid JSON. No markdown, no explanations.`;
}

/**
 * Combines system and user prompts into the format expected by
 * the AI SDK (Anthropic / OpenAI).
 *
 * Pure function — no side effects.
 */
export function buildSummarisationMessages(params: PromptInput): Array<{
  role: "system" | "user";
  content: string;
}> {
  return [
    { role: "system", content: buildSummarisationSystemPrompt() },
    { role: "user", content: buildSummarisationUserPrompt(params) },
  ];
}
