import { describe, it, expect } from "vitest";
import { generateProvenanceMetadata } from "./provenance";

describe("generateProvenanceMetadata", () => {
  const mockInput = {
    summary: {
      summaryText:
        "This is a comprehensive summary of the article covering all major points and findings.",
      keyPoints: ["Point one", "Point two"],
      sourcesCited: [
        { url: "https://example.com/source", title: "Source Title" },
      ],
      aiStatement: "Generated by AI model v1.0",
      coveragePercentage: 85,
    },
    articleId: "123e4567-e89b-12d3-a456-426614174000",
    articleUrl: "https://onestopnews.com/article/123",
    articleTitle: "Test Article",
    model: "claude-4",
    generatedAt: "2024-06-01T12:00:00Z",
  };

  it("generates all three layers", () => {
    const result = generateProvenanceMetadata(mockInput);
    expect(result.jsonLd).toBeDefined();
    expect(result.httpHeader).toBeDefined();
    expect(result.metaTag).toBeDefined();
  });

  it("generates valid JSON-LD", () => {
    const result = generateProvenanceMetadata(mockInput);
    const jsonLd = JSON.parse(result.jsonLd);
    expect(jsonLd["@context"]).toBe("https://schema.org");
    expect(jsonLd["@type"]).toBe("CreativeWork");
    expect(jsonLd.name).toBe(mockInput.articleTitle);
  });

  it("generates base64-encoded HTTP header", () => {
    const result = generateProvenanceMetadata(mockInput);
    const decoded = JSON.parse(atob(result.httpHeader));
    expect(decoded.model).toBe(mockInput.model);
    expect(decoded.compliance).toBe("eu-ai-act-art50");
  });

  it("generates semicolon-delimited meta tag", () => {
    const result = generateProvenanceMetadata(mockInput);
    expect(result.metaTag).toContain("model:claude-4");
    expect(result.metaTag).toContain("compliance:eu-ai-act-art50");
  });

  it("includes model name in accountablePerson.name per PAD §8.4", () => {
    const result = generateProvenanceMetadata(mockInput);
    const jsonLd = JSON.parse(result.jsonLd);
    expect(jsonLd.accountablePerson.name).toBe(`AI System: ${mockInput.model}`);
  });
});
