/**
 * summarize.test.ts — Tests for the AI summarization module.
 *
 * Mocks the Vercel AI SDK (`ai`) and provider packages (`@ai-sdk/anthropic`,
 * `@ai-sdk/openai`) to isolate the summarization logic from real API calls.
 * Tests verify:
 *   - Anthropic is called as primary provider with correct schema + messages
 *   - OpenAI is called as fallback when Anthropic throws
 *   - Both providers failing propagates the error
 *   - Article body is used as content when available
 *   - Excerpt is used as fallback content when body is null
 *   - Return shape includes model + tokensUsed
 */

import { describe, it, expect, vi, beforeEach } from "vitest";

// ── Mock the AI SDK and providers ──────────────────────────────────────────
// generateObject is the function under test — we mock its implementation
// to simulate success/failure without real API calls.
const mockGenerateObject = vi.fn();
vi.mock("ai", () => ({
  generateObject: mockGenerateObject,
}));

// Provider factories return opaque "model" tokens — we just need them to
// be callable and return something identifiable for assertions.
const mockAnthropicModel = { id: "anthropic:claude-haiku-4-5" };
const mockOpenaiModel = { id: "openai:gpt-5-mini" };
vi.mock("@ai-sdk/anthropic", () => ({
  anthropic: vi.fn((modelId: string) => ({ ...mockAnthropicModel, modelId })),
}));
vi.mock("@ai-sdk/openai", () => ({
  openai: vi.fn((modelId: string) => ({ ...mockOpenaiModel, modelId })),
}));

// Import AFTER mocks are registered.
const { callAISummary } = await import("./summarize");
import type { ArticleForSummarization } from "./summarize";

// ── Test fixtures ──────────────────────────────────────────────────────────
const validSummaryOutput = {
  summaryText:
    "This is a comprehensive summary of the article covering all major points and findings in neutral tone.",
  keyPoints: ["Point one", "Point two"],
  sourcesCited: [{ url: "https://example.com/source", title: "Source Title" }],
  aiStatement: "Generated by AI model. Verify facts with original source.",
  coveragePercentage: 85,
};

const baseArticle: ArticleForSummarization = {
  title: "Test Article Title",
  excerpt: "Short excerpt of the article.",
  body: "Full body text of the article with sufficient content for summarization.",
  sourceName: "Test Source",
  sourceUrl: "https://example.com",
};

beforeEach(() => {
  vi.clearAllMocks();
  // Default: Anthropic succeeds
  mockGenerateObject.mockResolvedValue({
    object: validSummaryOutput,
    usage: { totalTokens: 250 },
  });
});

describe("callAISummary", () => {
  it("calls Anthropic generateObject with the summarisation schema and messages", async () => {
    await callAISummary(baseArticle);

    expect(mockGenerateObject).toHaveBeenCalledTimes(1);
    const callArgs = mockGenerateObject.mock.calls[0]?.[0];
    expect(callArgs).toBeDefined();
    expect(callArgs.model).toBeDefined(); // Anthropic model
    expect(callArgs.schema).toBeDefined(); // Zod schema
    expect(callArgs.messages).toBeDefined(); // System + user prompts
    expect(callArgs.temperature).toBe(0.1); // Factual-only mode
  });

  it("returns validated SummarisationOutput plus model + tokensUsed on Anthropic success", async () => {
    const result = await callAISummary(baseArticle);

    expect(result.summaryText).toBe(validSummaryOutput.summaryText);
    expect(result.keyPoints).toEqual(validSummaryOutput.keyPoints);
    expect(result.sourcesCited).toEqual(validSummaryOutput.sourcesCited);
    expect(result.aiStatement).toBe(validSummaryOutput.aiStatement);
    expect(result.coveragePercentage).toBe(validSummaryOutput.coveragePercentage);
    expect(result.model).toBe("claude-haiku-4-5");
    expect(result.tokensUsed).toBe(250);
  });

  it("falls back to OpenAI when Anthropic throws", async () => {
    // First call (Anthropic) rejects; second call (OpenAI) succeeds
    mockGenerateObject
      .mockRejectedValueOnce(new Error("Anthropic API rate limit"))
      .mockResolvedValueOnce({
        object: { ...validSummaryOutput, aiStatement: "OpenAI fallback" },
        usage: { totalTokens: 180 },
      });

    const result = await callAISummary(baseArticle);

    expect(mockGenerateObject).toHaveBeenCalledTimes(2);
    expect(result.model).toBe("gpt-5-mini");
    expect(result.tokensUsed).toBe(180);
    expect(result.aiStatement).toBe("OpenAI fallback");
  });

  it("throws when both Anthropic and OpenAI fail", async () => {
    mockGenerateObject
      .mockRejectedValueOnce(new Error("Anthropic down"))
      .mockRejectedValueOnce(new Error("OpenAI also down"));

    await expect(callAISummary(baseArticle)).rejects.toThrow(/OpenAI also down/);
  });

  it("uses article body as content when available", async () => {
    await callAISummary(baseArticle);

    const callArgs = mockGenerateObject.mock.calls[0]?.[0];
    const userMessage = callArgs.messages.find(
      (m: { role: string }) => m.role === "user"
    );
    expect(userMessage.content).toContain(baseArticle.body);
  });

  it("falls back to excerpt when body is null", async () => {
    const articleNoBody: ArticleForSummarization = {
      ...baseArticle,
      body: null,
    };

    await callAISummary(articleNoBody);

    const callArgs = mockGenerateObject.mock.calls[0]?.[0];
    const userMessage = callArgs.messages.find(
      (m: { role: string }) => m.role === "user"
    );
    expect(userMessage.content).toContain(baseArticle.excerpt);
  });

  it("falls back to title when both body and excerpt are null", async () => {
    const articleTitleOnly: ArticleForSummarization = {
      ...baseArticle,
      body: null,
      excerpt: null,
    };

    await callAISummary(articleTitleOnly);

    const callArgs = mockGenerateObject.mock.calls[0]?.[0];
    const userMessage = callArgs.messages.find(
      (m: { role: string }) => m.role === "user"
    );
    expect(userMessage.content).toContain(baseArticle.title);
  });

  it("passes source name and URL in the prompt for citation context", async () => {
    await callAISummary(baseArticle);

    const callArgs = mockGenerateObject.mock.calls[0]?.[0];
    const userMessage = callArgs.messages.find(
      (m: { role: string }) => m.role === "user"
    );
    expect(userMessage.content).toContain(baseArticle.sourceName);
    expect(userMessage.content).toContain(baseArticle.sourceUrl);
  });
});
